### ISSUE TITLE
PA REVIEW: Comments

### ISSUE THREAD

**Issue by gabrieltal** [gabrieltal/betwixt#10]
- [x] Logged in users can write comments on stories
- [x] Logged out users cannot write or submit any comments
- [x] Styled
- [x] Comments update after submitting a new comment
- [x] Users not logged in are given a modal to sign in with different text than if signing up or logging in normally

**Comment by wongshington** [comment]
- [x] on the modal that pops up when you try and comment make the title that says "must be logged into comment" stand out a bit more from the rest of the text
- [x] if im trying to comment while not logged in, but then i hit demo signup, it still flashes the modal to sign in even though I am now signed in
