### ISSUE TITLE
New story bug

### ISSUE THREAD

**Issue by ghost** [gabrieltal/betwixt#13]
Cant create story on any page.When i click new story just blank page coming up.After that i click back (i must be on main page normally) its blank page again.I must refresh the page for normal main page.

**Comment by gabrieltal** [comment]
Hmm. I was able to publish a new story just fine. http://things-betwixt.herokuapp.com/#/story/13. Just added that. Are you having this issue in a local development environment? I'll try to spin it up later today and see if I am having issues too. If you could give me more information about the issue that would be good cause at least on the production site there is no issue.

**Comment by ghost** [comment]
Yep its on my localhost.

**Comment by ghost** [comment]
Ive looked up /#/story/new 's html file and no body content.Probably u forgot copying a code and your original version still working very well.Can u check that?

**Comment by gabrieltal** [comment]
I'm guessing you're most likely missing some configuration I had set up in my project. I think I was connected to an amazon S3 bucket that you'll probably need to set up on your own. I'll have to run the project locally and see what I can find that you're probably missing in your setup. 

What I have on github is what is deployed to the production site. I don't think there is anything that is missing on the repo. I am almost certain you're missing something as part of the setup which is my fault for not having this included in the readme but to be fair I never really thought anyone would clone this repo and try running it on their own.

**Comment by ghost** [comment]
Maybe aws can cause that but all of other functions working well.This page s the only failed place

**Comment by ghost** [comment]
I deploy it to AWS and no problem with new story thing.Its just weird localhost bug guys.Repo working on AWS perfectly.
